package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/heruujoko/federated-monorepo/customers-service/graph/generated"
	"github.com/heruujoko/federated-monorepo/customers-service/internal"
	"github.com/heruujoko/federated-monorepo/customers-service/model"
)

// Foo is the resolver for the foo field.
func (r *queryResolver) Foo(ctx context.Context, id string) (*model.Foo, error) {
	return FindFoo(id)
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	customers, err := internal.ResolveCustomers()
	return customers, err
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
